:toc:
:toc-placement:
:sectnums: |,all|
toc::[]

== Option A

This example shows how to test HTTP error in Mule 4 with Munit 2.

If you encounter this issue

```bash
org.mule.runtime.api.exception.MuleRuntimeException: org.mule.runtime.core.api.config.ConfigurationException: [option-a/implementation-test-suite.xml:42]: Referenced component 'munit-util-mock-http-error-with-errorMessage-test-suite.listener-flow' must be one of stereotypes [MULE:FLOW, MULE:SUB_FLOW].
[option-a/implementation-test-suite.xml:114]: Referenced component 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' must be one of stereotypes [MULE:FLOW].
[option-a/implementation-test-suite.xml:188]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist
[option-a/implementation-test-suite.xml:218]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist
Caused by: org.mule.runtime.core.api.config.ConfigurationException: [option-a/implementation-test-suite.xml:42]: Referenced component 'munit-util-mock-http-error-with-errorMessage-test-suite.listener-flow' must be one of stereotypes [MULE:FLOW, MULE:SUB_FLOW].
[option-a/implementation-test-suite.xml:114]: Referenced component 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' must be one of stereotypes [MULE:FLOW].
[option-a/implementation-test-suite.xml:188]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist
[option-a/implementation-test-suite.xml:218]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist


WARN  2025-09-26 15:41:01,116 [munit.01] org.mule.runtime.config.internal.context.MuleArtifactContext: [option-a/implementation-test-suite.xml:117]: Referenced component 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' must be one of stereotypes [MULE:FLOW].
org.mule.runtime.api.exception.MuleRuntimeException: org.mule.runtime.core.api.config.ConfigurationException: [option-a/implementation-test-suite.xml:117]: Referenced component 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' must be one of stereotypes [MULE:FLOW].
[option-a/implementation-test-suite.xml:191]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist
[option-a/implementation-test-suite.xml:221]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist
Caused by: org.mule.runtime.core.api.config.ConfigurationException: [option-a/implementation-test-suite.xml:117]: Referenced component 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' must be one of stereotypes [MULE:FLOW].
[option-a/implementation-test-suite.xml:191]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist
[option-a/implementation-test-suite.xml:221]: 'flow-ref' is pointing to 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' which does not exist
```

It's important to enable the flows that will be used in the test

```xml
    <munit:enable-flow-sources>
      <munit:enable-flow-source
        value="munit-util-mock-http-error-with-errorMessage-test-suite.listener-flow" />
      <munit:enable-flow-source
        value="munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow" />
    </munit:enable-flow-sources>
```

If this error persist in some way, you may move the flows from one file to the same where the munit test, but in this case you will need to concentrate all munit tests in one test suite only.

You may think in Import the other file, but this doesn't work his is a Bug and you will need to Import the file that has the flows for the Request and Listener:

```xml
<import
    doc:name="Import"
    file="option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml"
    doc:description="munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml" />
````

When Running in Studio or using maven `mvn clean test` you will need to comment or remove the `import`, otherwise will get an error like:

```bash
org.mule.runtime.api.exception.MuleRuntimeException: org.mule.runtime.core.api.config.ConfigurationException: [option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:27; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:27]: Two (or more) configuration elements have been defined with the same global name. Global name 'MUnit_HTTP_Listener_config' must be unique.
[option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:36; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:36]: Two (or more) configuration elements have been defined with the same global name. Global name 'MUnit_HTTP_Request_configuration' must be unique.
[option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:43; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:43]: Two (or more) configuration elements have been defined with the same global name. Global name 'munit-util-mock-http-error-with-errorMessage-test-suite.listener-flow' must be unique.
[option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:67; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:67]: Two (or more) configuration elements have been defined with the same global name. Global name 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' must be unique.
Caused by: org.mule.runtime.core.api.config.ConfigurationException: [option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:27; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:27]: Two (or more) configuration elements have been defined with the same global name. Global name 'MUnit_HTTP_Listener_config' must be unique.
[option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:36; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:36]: Two (or more) configuration elements have been defined with the same global name. Global name 'MUnit_HTTP_Request_configuration' must be unique.
[option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:43; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:43]: Two (or more) configuration elements have been defined with the same global name. Global name 'munit-util-mock-http-error-with-errorMessage-test-suite.listener-flow' must be unique.
[option-a/munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:67; option-a\munit-util-mock-http-request-for-errorMessage-using-listener-localhost-test-suite.xml:67]: Two (or more) configuration elements have been defined with the same global name. Global name 'munit-util-mock-http-error-with-errorMessage-test-suite.req-based-on-vars.munitHttpMock-flow' must be unique.
INFO  2025-09-26 14:40:26,253 [munit.01] org.mule.munit.runner.remote.api.server.RunnerServer: Waiting for client connection
```

So, you could leave the file in `src/main/mule`, but it's important to


=== Dynamic Port

This approach use the dynamic port feature from MUnit

https://docs.mulesoft.com/munit/latest/dynamic-ports




== Option B

A simple flow and munit test similar to the option B, but in this case the HTTP Listener is in a flow inside  is on `src/main/`

Original source code: link:https://help.salesforce.com/s/articleView?id=001117133&type=1[How to test HTTP error in Mule 4 with Munit 2]

In this option is important to consider move the flow for HTTP Listener from `munitusage.xml` in the directory `src\main\mule\option-b` so the flow and the respective configuration goes to `src/test/munit/option-b`.
This avoid any invalid usage or even the deploy on Mule Runtime.

You may add to your `pom.xml` file to ignore the file in the build:

```xml
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.4.2</version>
                    <configuration>
                        <excludes>
                            <exclude>option-b\munitusage.xml</exclude>
                        </excludes>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
```


